language: python
python: 3.7
dist: xenial
sudo: true

install:
  - pip install pip -U
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install -v

script: pytest -q aioetherscan/tests/