language: python
python:
  - "3.7"
  - "3.8"
dist: xenial
sudo: true

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

install:
  - pip install pip -U
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -v

script: pytest -q aioetherscan/tests/

after_success:
  - poetry run coverage run --source=aioetherscan -m pytest
  - coveralls