[tool.poetry]
name = "aioetherscan"
version = "0.1.0"
description = "Etherscan API async Python wrapper"
authors = ["ape364 <ape364@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.4"

[tool.poetry.dev-dependencies]
pytest = "^4.0"
pytest-asyncio = "^0.9.0"
asynctest = "^0.12.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
